import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export interface EmailParams {
  to: string;
  subject: string;
  html: string;
  courseId?: string;
  courseTitle?: string;
}

export async function sendReminderEmail(params: EmailParams): Promise<{ success: boolean; messageId?: string; error?: string }> {
  try {
    const { data, error } = await resend.emails.send({
      from: process.env.FROM_EMAIL || 'noreply@yourdomain.com',
      to: [params.to],
      subject: params.subject,
      html: params.html,
    });

    if (error) {
      console.error('Resend error:', error);
      return { success: false, error: error.message };
    }

    return { success: true, messageId: data?.id };
  } catch (error) {
    console.error('Email sending error:', error);
    return { 
      success: false, 
      error: error instanceof Error ? error.message : 'Unknown error occurred' 
    };
  }
}

export function createEmailTemplate(context: {
  userName: string;
  courseTitle: string;
  courseId: string;
  progressPercent: number;
  completedVideos: number;
  totalVideos: number;
  body: string; // Generated by Gemini
}): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${context.courseTitle} - Study Reminder</title>
    </head>
    <body style="margin: 0; padding: 0; background-color: #ffffff; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; color: #333333; line-height: 1.6;">
      <div style="max-width: 600px; margin: 0 auto; padding: 20px;">
        
        <!-- Main Content -->
        <div style="padding: 0;">
          ${context.body}
          
          <!-- Progress Bar -->
          <div style="margin: 30px 0; padding: 15px 0; border-top: 1px solid #e5e5e5; border-bottom: 1px solid #e5e5e5;">
            <p style="margin: 0 0 10px 0; color: #333; font-size: 14px; font-weight: 500;">Your Progress</p>
            <div style="background-color: #e5e5e5; height: 8px; border-radius: 4px; overflow: hidden; margin-bottom: 8px;">
              <div style="background-color: #0066cc; height: 100%; width: ${context.progressPercent}%;"></div>
            </div>
            <p style="margin: 0; color: #666; font-size: 13px;">
              ${context.completedVideos} of ${context.totalVideos} videos completed (${context.progressPercent}%)
            </p>
          </div>
          
          <!-- Simple Link -->
          <div style="margin: 25px 0;">
            <a href="${process.env.NEXTAUTH_URL}/courses/${context.courseId}" 
               style="color: #0066cc; text-decoration: underline; font-size: 14px;">
              Continue Learning →
            </a>
          </div>
          
          <!-- Footer -->
          <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e5e5;">
            <p style="color: #999; font-size: 12px; margin: 0; line-height: 1.5;">
              You're receiving this because you have email notifications enabled for this course.<br>
              <a href="${process.env.NEXTAUTH_URL}/courses/${context.courseId}" style="color: #0066cc; text-decoration: underline;">Manage notification settings</a>
            </p>
          </div>
        </div>
      </div>
    </body>
    </html>
  `;
}
